CREATE TABLE [dbo].[fato_operacoes_recompra] (

	[cod_operacao] int NULL, 
	[cod_empresa] int NULL, 
	[cod_cliente] int NULL, 
	[cpf_cnpj_cliente] varchar(8000) NULL, 
	[usua_st_analise] int NULL, 
	[data_analise] datetime2(6) NULL, 
	[data_aceite] datetime2(6) NULL, 
	[stto] varchar(8000) NULL, 
	[fator] decimal(38,6) NULL, 
	[tarifa] decimal(38,6) NULL, 
	[tarifa_recompra] decimal(38,6) NULL, 
	[n_docs] int NULL, 
	[n_docs_recompra] int NULL, 
	[pmp] decimal(38,6) NULL, 
	[tot_adval] decimal(38,6) NULL, 
	[tot_tar] decimal(38,6) NULL, 
	[nota_fiscal] int NULL, 
	[usua_trava] int NULL, 
	[data_inclusao] datetime2(6) NULL, 
	[usua_inclusao] int NULL, 
	[data_alteracao] datetime2(6) NULL, 
	[nota_servico] varchar(8000) NULL, 
	[contrato_fisico] varchar(8000) NULL, 
	[n_bordero] int NULL, 
	[tto] varchar(8000) NULL, 
	[operacao_informal] bit NULL, 
	[cod_gerente] int NULL, 
	[cod_titulo] int NULL, 
	[n_doc] varchar(8000) NULL, 
	[cpf_cnpj_sacado] varchar(8000) NULL, 
	[cpf_cnpj_cedente] varchar(8000) NULL, 
	[valor] decimal(38,6) NULL, 
	[amortizacoes] decimal(38,6) NULL, 
	[liquidacao] datetime2(6) NULL
);